---
- name: launch rvi on localhost and in vagrant
  hosts: vagrant
  vars_prompt:
    - name: ansible_ssh_user
      prompt: "Local user name"
      private: no
    - name: registry_user
      prompt: "Docker Hub user name"
      private: no
    - name: registry_password
      prompt: "Docker Hub password"
      private: yes
    - name: registry_email
      prompt: "Docker Hub email"
      private: no
    - name: feeder_data_dir
      prompt: "Feeder data"
      default: /var/lib/traces
      private: no
  vars:
    - rvi_api_uri: "{{ hostvars[inventory_hostname].ansible_ssh_host }}"
  roles:
    - zookeeper
    - kafka
    - cassandra
    - docker-hub
    - { role: rvi-data-feeds, data_volume: "{{ feeder_data_dir }}" }
    - rvi-data-ingestion
    - rvi-api
    - rvi-ui
