---
- name: launch containers
  hosts: rvi
  vars_prompt:
    - name: registry_user
      prompt: "Docker Hub user name"
      private: no
      default: koshelev
    - name: registry_password
      prompt: "Docker Hub password"
      private: yes
    - name: registry_email
      prompt: "Docker Hub email"
      default: vr.koshelev@gmail.com
      private: no
  vars:
    ansible_ssh_user: core
    ansible_python_interpreter: "PATH=/home/core/bin:$PATH python"
  tasks:
    - name: pull zookeeper image
      raw: docker pull advancedtelematic/zookeeper
    - name: launch zookeeper
      docker:
        image="advancedtelematic/zookeeper"
        name="zookeeper"
        ports="2181:2181"
        state=running
    - name: pull kafka image
      raw: docker pull ches/kafka
    - name: launch kafka
      docker:
        image="ches/kafka"
        name="kafka"
        links="zookeeper:zookeeper"
        ports="9092:9092"
        state=running
    - name: pull cassandra image
      raw: docker pull poklet/cassandra
    - name: launch cassandra
      docker:
        image: "poklet/cassandra"
        name: "cassandra"
        ports:
          - 9042:9042
          - 9160:9160
        volumes:
          - /var/lib/cassandra
        state: running
    - name: Copy DB scripts
      copy: src="scripts" dest="/home/core" owner="core"
    - name: Wait for cassandra
      wait_for: host=localhost port=9042 delay=30 timeout=60 state=started
    - name: Create DB schema
      raw: docker run -it --rm --link cassandra:cassandra -v /home/core/scripts:/data poklet/cassandra bash -c 'cqlsh $CASSANDRA_PORT_9160_TCP_ADDR -f /data/schema.cql'

    - name: login into Docker Hub
      raw: docker login -u {{ registry_user }} -p {{ registry_password }} -e {{ registry_email}}
    - name: pull feeder image
      raw: docker pull advancedtelematic/rvi_data_feeds
#    - name: Import data
#      raw: docker run --rm -i -t --link=cassandra:cassandra advancedtelematic/rvi_data_feeds /opt/docker/bin/data-feeds -main com.advancedtelematic.feed.CassandraFeeder

    - name: pull api image
      raw: docker pull advancedtelematic/rvi_data_api
    - name: launch api
      docker:
        image: "advancedtelematic/rvi_data_api"
        name: api
        ports:
          - 9000:9000
        links:
          - cassandra:cassandra
          - zookeeper:zk
        state: running
      register: api_container

#    - name: pull ui image
#      raw: docker pull advancedtelematic/rvi_demo_ui:0.5.3
    - name: launch ui
      docker:
        image: "advancedtelematic/rvi_demo_ui:0.5.3"
        name: ui
        expose: 10555
        ports:
          - 10555:10555
        env:
          TRACES_URI: ws://{{ hostvars[inventory_hostname].ansible_ssh_host }}:9000/ws
          API_URI: http://{{ hostvars[inventory_hostname].ansible_ssh_host }}:9000/
        state: running

    - name: start data feeds
      docker:
        image: "advancedtelematic/rvi_data_feeds"
        name: feeds
        links:
          - kafka:kafka
        state: running
