---
- name: launch containers
  hosts: local:coreos
  vars_prompt:
    - name: registry_user
      prompt: "Docker Hub user name"
      private: no
    - name: registry_password
      prompt: "Docker Hub password"
      private: yes
    - name: registry_email
      prompt: "Docker Hub email"
      private: no
  tasks:
    # external software
    - include: tasks/launch-zookeper.yml
    - include: tasks/launch-kafka.yml
    - include: tasks/launch-cassandra.yml

    # try to log in to docker.io
    - include: tasks/docker-login.yml

    # data feeds
    - include: tasks/pull-data-feeds.yml
    - include: tasks/import-historical-data.yml
    - include: tasks/run-data-feeds.yml

    # api
    - include: tasks/launch-api.yml

    # ui
    - include: tasks/pull-ui.yml
    - include: tasks/run-ui.yml

