---
- name: pull zookeeper image
  raw: docker pull advancedtelematic/zookeeper
- name: launch zookeeper
  docker:
    image: advancedtelematic/zookeeper
    name: zookeeper
    ports:
      - 2181:2181
    state: running
