---
- name: launch ui
  docker:
    image: "advancedtelematic/rvi_demo_ui:0.5.3"
    name: ui
    expose: 10555
    ports:
      - 10555:10555
    env:
      - TRACES_URI=ws://{{ hostvars[inventory_hostname].ansible_ssh_host }}:9000/ws
      - API_URI=http://{{ hostvars[inventory_hostname].ansible_ssh_host }}:9000/
    state: running
